"""Add user profile status for onboarding

Revision ID: 002
Revises: 001
Create Date: 2025-09-02 22:35:24.163684

"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: str | Sequence[str] | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles", sa.Column("preferred_name", sa.String(), nullable=True)
    )
    op.add_column("user_profiles", sa.Column("status", sa.String(), nullable=True))
    op.alter_column(
        "user_profiles", "first_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "user_profiles", "last_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("user_profiles", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user_profiles", "phone", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "user_profiles", "gender", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "user_profiles", "birth_date", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column("user_profiles", "bio", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_profiles", "bio", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "user_profiles", "birth_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "user_profiles", "gender", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "user_profiles", "phone", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "user_profiles", "email", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "user_profiles", "last_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "user_profiles", "first_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("user_profiles", "status")
    op.drop_column("user_profiles", "preferred_name")
    # ### end Alembic commands ###
