from enum import Enum


class MemoryType(Enum):
    """External events, activities, interactions, and things that happened or are happening"""

    HAPPENINGS = "happenings"

    """Internal thoughts, feelings, realizations, emotional states, and mental experiences"""
    REFLECTIONS = "reflections"

    """External environment, context, things noticed, and situational awareness"""
    OBSERVATIONS = "observations"


class MemoryTag(Enum):
    # People & Relationships
    """Family members"""

    FAMILY = "family"
    """Parent figures"""
    PARENTS = "parents"
    """Brothers or sisters"""
    SIBLINGS = "siblings"
    """Offspring"""
    CHILDREN = "children"
    """Romantic partner"""
    PARTNER = "partner"
    """Married partner"""
    SPOUSE = "spouse"
    """Close personal friends"""
    FRIENDS = "friends"
    """Work associates"""
    COLLEAGUES = "colleagues"
    """Workplace supervisor"""
    BOSS = "boss"
    """Business clients"""
    CLIENTS = "clients"
    """Unknown people"""
    STRANGERS = "strangers"
    """People living nearby"""
    NEIGHBORS = "neighbors"

    # Emotional States
    """Positive emotional state"""
    HAPPY = "happy"
    """Negative emotional state"""
    SAD = "sad"
    """Worried or nervous feeling"""
    ANXIOUS = "anxious"
    """Enthusiastic or thrilled feeling"""
    EXCITED = "excited"
    """Annoyed or irritated feeling"""
    FRUSTRATED = "frustrated"
    """Mad or upset feeling"""
    ANGRY = "angry"
    """Satisfied or peaceful feeling"""
    CONTENT = "content"
    """Under pressure or tension"""
    STRESSED = "stressed"
    """Peaceful or relaxed feeling"""
    CALM = "calm"
    """Feeling swamped or burdened"""
    OVERWHELMED = "overwhelmed"
    """Feeling accomplished or pleased"""
    PROUD = "proud"
    """Let down or dissatisfied feeling"""
    DISAPPOINTED = "disappointed"

    # Activities & Actions
    """Professional work activities"""
    WORK = "work"
    """Formal gathering or discussion"""
    MEETING = "meeting"
    """Electronic correspondence"""
    EMAIL = "email"
    """Phone or video conversation"""
    CALL = "call"
    """Physical fitness activities"""
    EXERCISE = "exercise"
    """Food preparation"""
    COOKING = "cooking"
    """Consuming food"""
    EATING = "eating"
    """Journey or trip"""
    TRAVEL = "travel"
    """Operating a vehicle"""
    DRIVING = "driving"
    """Moving on foot"""
    WALKING = "walking"
    """Acquiring knowledge"""
    LEARNING = "learning"
    """Reading text"""
    READING = "reading"
    """Viewing content"""
    WATCHING = "watching"
    """Purchasing items"""
    SHOPPING = "shopping"
    """Tidying or organizing"""
    CLEANING = "cleaning"

    # Physical States
    """Feeling exhausted or sleepy"""
    TIRED = "tired"
    """Feeling vigorous or lively"""
    ENERGETIC = "energetic"
    """Feeling unwell"""
    SICK = "sick"
    """Feeling well"""
    HEALTHY = "healthy"
    """Physical discomfort"""
    PAIN = "pain"
    """Head pain"""
    HEADACHE = "headache"
    """Need for food"""
    HUNGRY = "hungry"
    """Satisfied after eating"""
    FULL = "full"
    """Need for water"""
    THIRSTY = "thirsty"
    """Feeling warm temperature"""
    HOT = "hot"
    """Feeling cool temperature"""
    COLD = "cold"

    # Locations
    """Personal residence"""
    HOME = "home"
    """Workplace location"""
    OFFICE = "office"
    """Dining establishment"""
    RESTAURANT = "restaurant"
    """Fitness facility"""
    GYM = "gym"
    """Outside spaces"""
    OUTDOORS = "outdoors"
    """Personal vehicle"""
    CAR = "car"
    """Aircraft"""
    PLANE = "plane"
    """Temporary accommodation"""
    HOTEL = "hotel"
    """Medical facility"""
    HOSPITAL = "hospital"
    """Retail location"""
    STORE = "store"
    """Public green space"""
    PARK = "park"
    """Coastal area"""
    BEACH = "beach"

    # Health & Wellness
    """Medical treatments"""
    MEDICATION = "medication"
    """Health issues"""
    SYMPTOMS = "symptoms"
    """Medical professional"""
    DOCTOR = "doctor"
    """Scheduled medical visit"""
    APPOINTMENT = "appointment"
    """Mental health treatment"""
    THERAPY = "therapy"
    """Rest period"""
    SLEEP = "sleep"
    """Difficulty sleeping"""
    INSOMNIA = "insomnia"
    """Food and eating habits"""
    DIET = "diet"
    """Nutritional intake"""
    NUTRITION = "nutrition"
    """Water consumption"""
    HYDRATION = "hydration"

    # Work & Professional
    """Work assignment"""
    PROJECT = "project"
    """Time constraint"""
    DEADLINE = "deadline"
    """Formal presentation"""
    PRESENTATION = "presentation"
    """Job advancement"""
    PROMOTION = "promotion"
    """Job application process"""
    INTERVIEW = "interview"
    """Professional development"""
    TRAINING = "training"
    """Professional event"""
    CONFERENCE = "conference"
    """Working together"""
    COLLABORATION = "collaboration"

    # Goals & Progress
    """Accomplishing something"""
    ACHIEVEMENT = "achievement"
    """Moving forward"""
    PROGRESS = "progress"
    """Encountering obstacles"""
    SETBACK = "setback"
    """Making plans"""
    PLANNING = "planning"
    """Drive to succeed"""
    MOTIVATION = "motivation"
    """Developing abilities"""
    SKILL = "skill"
    """Personal interests"""
    HOBBY = "hobby"
    """Regular behavior"""
    HABIT = "habit"

    # Contextual Environment
    """Atmospheric conditions"""
    WEATHER = "weather"
    """Vehicle congestion"""
    TRAFFIC = "traffic"
    """Sound level"""
    NOISE = "noise"
    """Many people present"""
    CROWDED = "crowded"
    """Peaceful environment"""
    QUIET = "quiet"
    """Aesthetically pleasing"""
    BEAUTIFUL = "beautiful"
    """Causing stress"""
    STRESSFUL = "stressful"
    """Causing relaxation"""
    RELAXING = "relaxing"
    """High significance"""
    IMPORTANT = "important"
    """Requiring immediate attention"""
    URGENT = "urgent"
