from enum import Enum


class UserEntityCollection(Enum):
    """Core self-concept including demographics, physical traits, personality, values, and beliefs"""

    IDENTITY = "identity"

    """All relationship and social connections including family, friends, pets, and community involvement"""
    SOCIAL = "social"

    """Work, education, skills, career development, and professional achievements"""
    PROFESSIONAL = "professional"

    """Physical/mental health, fitness, nutrition, wellness practices, and health-related habits"""
    HEALTH = "health"

    """Living situation, daily routines, preferences, and lifestyle choices that define how one lives"""
    LIFESTYLE = "lifestyle"

    """Goals, interests, hobbies, learning activities, and personal growth pursuits"""
    PURSUITS = "pursuits"

    """Financial status, material possessions, and quantifiable personal metrics"""
    RESOURCES = "resources"

    """Significant life events, achievements, transitions, and memorable experiences"""
    MILESTONES = "milestones"

    """Miscellaneous information that doesn't clearly fit into other dense categories"""
    MISC = "misc"


class UserEntityType(Enum):
    FATHER = "father"
    MOTHER = "mother"
    SPOUSE = "spouse"
    PARTNER = "partner"
    BIRTH_DATE = "birth_date"
    BIRTH_PLACE = "birth_place"
    PRIMARY_JOB = "primary_job"
    CURRENT_EMPLOYER = "current_employer"
    PRIMARY_PHONE = "primary_phone"
    PRIMARY_EMAIL = "primary_email"
    PRIMARY_ADDRESS = "primary_address"
    HOME_ADDRESS = "home_address"
    PRIMARY_RESIDENCE = "primary_residence"
    BLOOD_TYPE = "blood_type"
    HEIGHT = "height"
    PRIMARY_DOCTOR = "primary_doctor"
    TIMEZONE = "timezone"
    PREFERRED_LANGUAGE = "preferred_language"

    GOAL = "goal"
    ASPIRATION = "aspiration"
    MILESTONE = "milestone"
    ACHIEVEMENT = "achievement"
    FRIEND = "friend"
    COLLEAGUE = "colleague"
    ACQUAINTANCE = "acquaintance"
    MENTOR = "mentor"
    MENTEE = "mentee"
    NEIGHBOR = "neighbor"
    SIBLING = "sibling"
    CHILD = "child"
    GRANDPARENT = "grandparent"
    AUNT = "aunt"
    UNCLE = "uncle"
    COUSIN = "cousin"
    SKILL = "skill"
    HOBBY = "hobby"
    INTEREST = "interest"
    TALENT = "talent"
    CERTIFICATION = "certification"
    LANGUAGE = "language"
    HEALTH_CONDITION = "health_condition"
    ALLERGY = "allergy"
    MEDICATION = "medication"
    SYMPTOM = "symptom"
    INJURY = "injury"
    TREATMENT = "treatment"
    JOB = "job"
    PREVIOUS_EMPLOYER = "previous_employer"
    EDUCATION = "education"
    DEGREE = "degree"
    COURSE = "course"
    PROJECT = "project"
    FOOD_PREFERENCE = "food_preference"
    DIETARY_RESTRICTION = "dietary_restriction"
    EXERCISE_ROUTINE = "exercise_routine"
    HABIT = "habit"
    ROUTINE = "routine"
    MEMBERSHIP = "membership"
    SUBSCRIPTION = "subscription"
    ACCOUNT = "account"
    DEVICE = "device"
    PROPERTY = "property"
    INVESTMENT = "investment"
    INSURANCE = "insurance"
    EVENT = "event"
    TRIP = "trip"
    EXPERIENCE = "experience"
    MEMORY = "memory"
    TRADITION = "tradition"
